### ISSUE TITLE
lint error on block JS

### ISSUE THREAD

**Issue by ajitbohra** [youknowriad/wp-js-plugin-starter#7]
Seems like `wp.element` is not required
https://github.com/youknowriad/wp-js-plugin-starter/blob/f55c00af6910ba3fcb06a82a4dfa2bcea9715533/src/index.js#L1

lint error for double quotes for string and no space around parathesis 
https://github.com/youknowriad/wp-js-plugin-starter/blob/f55c00af6910ba3fcb06a82a4dfa2bcea9715533/src/index.js#L4

https://github.com/youknowriad/wp-js-plugin-starter/blob/f55c00af6910ba3fcb06a82a4dfa2bcea9715533/src/index.js#L17

**Comment by youknowriad** [comment]
Actually, it is required. Each time you use JSX, you need `createElement` in the scope. 

In Gutenberg we overcome this using this babel transform https://github.com/WordPress/gutenberg/tree/master/packages/babel-plugin-import-jsx-pragma

but it's not usable in this repository because I don't have `@wordpress/element` => `wp.element` aliases. The babel transform needs to be updated to allow a global variable instead of an import to be usable in the setup of this starter.

**Comment by ajitbohra** [comment]
thanks for the clarification :)
